#!/usr/bin/env ruby

ENV['ROC_STORE'] ||= 'test'
#ENV['ROC_STORE'] ||= 'redis://127.0.0.1/1'

if ARGV.delete('gem')
  if RUBY_VERSION.match(/^1\.8/)
    require 'rubygems'
  end
else
  $:.unshift File.join(File.dirname(__FILE__), '..', 'lib')
end

testable = [
            'string',
            'integer',
            'float',
            'time',
            
            'list',
            'set',
            'sorted_set',
            
            'hash',
            
            'key_operations',
            'transactions',

            'transient_store'
            ]

to_test = testable & ARGV
if 0 == to_test.size
  to_test = testable
end
to_test.each do |t|
  puts "=== #{t}_test ==="
  require File.join('.', File.dirname(__FILE__), "#{t}_test")
end
