#!/usr/bin/env ruby

ENV['ROC_STORE'] ||= 'test'
#ENV['ROC_STORE'] ||= 'redis://127.0.0.1/1'

require File.join('.', File.dirname(__FILE__), 'key_operations_test')
require File.join('.', File.dirname(__FILE__), 'string_test')

##@@ iterate
